#!/bin/bash

bash_cmd="$*"

echo "You are about to run '$bash_cmd' as user $(whoami)"
read -p "Are you sure (y/n)? " choice

if [[ $choice =~ ^[Yy]$ ]]; then
    bash -c "$bash_cmd" && echo "success"
else
    echo "not done"
fi
