#!/bin/bash

wait_file() (
        local file="$1"

        if fuser "$(pwd)/$file"; then
            inotifywait -e close "$(pwd)/$file"
        fi

        if [[ "$file" =~ \.pdf$ ]] && lp "$file"; then
                echo "printing $file"
                mv "$file" .recycle
        else
                echo "unable to print $file"
                mv "$file" "UNDRUCKBAR $file"
        fi
)


inotifywait -m --format '%f' -e create . | while read file; do
        wait_file "$file" &
done
