#!/bin/bash

set -euo pipefail

action="$1"
pod_name="$2"

pod_infra=$(podman pod inspect "${pod_name}" | jq -re '.Containers | map(select(.Name | test(".*infra"))) | .[0].Name')
pod_addr=$(podman container inspect "${pod_infra}" | jq -re '.[0].NetworkSettings.IPAddress')

if [[ -z ${pod_addr} ]]; then
    echo 'Error: unable to find infra container' 1>&2
    exit 1
fi

case "$action" in
    -r)
        firewall-cmd --zone podman --remove-source "${pod_addr}/32"
        ;;
    -c)
        firewall-cmd --zone podman --change-source "${pod_addr}/32"
        ;;
    *)
        echo 'Error: invalid action, must be one of {-c, -r}' 1>&2
        exit 2
        ;;
esac
